SOLR-14768: Fix multipart POST to Solr. Regression from 8.6
Multipart POST would fail due to a NoClassDefFoundError of Jetty MultiPart.  Solr cannot access many Jetty classes, which is not noticeable in our tests.