LUCENE-9215: log errors about missing @param even when tree is null
This means on the first run, you'll see everything you need to fix (up to javadoc's limit)

Instead of:

> Task :lucene:memory:renderJavadoc FAILED
/home/rmuir/workspace/lucene-solr/lucene/memory/src/java/org/apache/lucene/index/memory/MemoryIndex.java:283: error - MemoryIndex.fromDocument (method): javadocs are missing
1 error

You now see:

> Task :lucene:memory:renderJavadoc FAILED
/home/rmuir/workspace/lucene-solr/lucene/memory/src/java/org/apache/lucene/index/memory/MemoryIndex.java:283: error - MemoryIndex.fromDocument (method): javadocs are missing
/home/rmuir/workspace/lucene-solr/lucene/memory/src/java/org/apache/lucene/index/memory/MemoryIndex.java:283: error - MemoryIndex.fromDocument (method): missing javadoc @param for parameter 'document'
/home/rmuir/workspace/lucene-solr/lucene/memory/src/java/org/apache/lucene/index/memory/MemoryIndex.java:283: error - MemoryIndex.fromDocument (method): missing javadoc @param for parameter 'analyzer'
3 errors

Previously the tooling would force you to do a second pass.