SOLR-14768: Fix multipart POST to Solr. (#1838)
Regression from 8.6
Multipart POST would fail due to a NoClassDefFoundError of Jetty MultiPart.  Solr cannot access many Jetty classes, which is not noticeable in our tests.

(cherry picked from commit 7b53671920840bb6fe6906436260d6bf906156f9)